---
- name: Add SSH key to agent
  hosts: localhost
  tags:
    - key
  tasks:
    - name: Add SSH key
      ansible.builtin.include_role:
        name: add_ssh_key


- name: Set up filebeat
  hosts: stack
  gather_facts: false
  roles:
    - role: filebeat
      tags:
        - filebeat

- name: Configure load balancer
  hosts: stack
  gather_facts: false
  roles:
    - role: haproxy
      tags:
        - haproxy

- name: Configure ChatOps
  hosts: stack
  gather_facts: false
  roles:
    - role: chatops
      tags:
        - chatops

- name: Configure CAdvisor
  hosts: stack
  gather_facts: false
  remote_user: ubuntu
  roles:
    - role: cadvisor
      tags:
        - cadvisor

- name: Set up systemd exporters
  hosts: stack
  gather_facts: false
  roles:
    - role: systemd_exporter
      tags:
        - systemd_exporter

- name: Set up node exporters
  hosts: stack
  gather_facts: false
  roles:
    - role: node_exporter
      tags:
        - node_exporter

- name: Configure Grafana
  hosts: stack
  gather_facts: false
  roles:
    - grafana
  tags:
    - grafana

- name: Attach volume
  hosts: stack
  gather_facts: true
  roles:
    - volume
  tags:
    - volume

- name: Configure Prometheus
  hosts: stack
  gather_facts: false
  roles:
    - prometheus
  tags:
    - prometheus

- name: Configure Alert Manager
  hosts: stack
  gather_facts: false
  roles:
    - alertmanager
  tags:
    - alertmanager

- name: Configure Elastic Stack
  hosts: stack
  gather_facts: false
  remote_user: ubuntu
  force_handlers: true
  roles:
    - elastic
  tags:
    - elastic
