---
- name: Configure load balancer
  hosts: stack
  roles:
    - role: haproxy
      tags:
        - haproxy

- name: Configure ChatOps
  hosts: stack
  roles:
    - role: chatops
      tags:
        - chatops

- name: Configure CAdvisor
  hosts: stack
  remote_user: ubuntu
  roles:
    - role: cadvisor
      tags:
        - cadvisor

- name: Set up systemd exporters
  hosts: stack
  roles:
    - role: systemd_exporter
      tags:
        - systemd_exporter

- name: Configure Grafana
  hosts: stack
  roles:
    - grafana
  tags:
    - grafana

- name: Configure Prometheus
  hosts: stack
  roles:
    - prometheus
  tags:
    - prometheus

- name: Configure Alert Manager
  hosts: stack
  roles:
    - alertmanager
  tags:
    - alertmanager

- name: Configure Elastic Stack
  hosts: stack
  remote_user: ubuntu
  force_handlers: true
  roles:
    - elastic
