---
- name: Configure load balancer
  hosts: loadbalancer
  remote_user: ubuntu
  roles:
    - role: loadbalancer
      tags:
        - loadbalancer

- name: Configure ChatOps
  hosts: chatops
  remote_user: ubuntu
  roles:
    - role: chatops
      tags:
        - chatops

- name: Set up systemd exporters
  hosts: all
  remote_user: ubuntu
  roles:
    - role: systemd_exporter
      tags:
        - systemd_exporter

- name: Configure Grafana
  hosts: grafana
  remote_user: ubuntu
  roles:
    - grafana
  tags:
    - grafana

- name: Configure Prometheus
  hosts: prometheus
  remote_user: ubuntu
  roles:
    - prometheus
  tags:
    - prometheus

- name: Configure Alert Manager
  hosts: prometheus
  remote_user: ubuntu
  roles:
    - alertmanager
  tags:
    - alertmanager
