---
- name: Deploy infrastructure
  hosts: localhost
  tasks:
    - name: Include Terraform deploy play
      ansible.builtin.include_role:
        name: terraform
        tasks_from: deploy

- name: Add SSH key to agent
  hosts: localhost
  tasks:
    - name: Add SSH key
      ansible.builtin.include_role:
        name: add_ssh_key

- name: Add known host of stack VM
  hosts: localhost
  gather_facts: false
  roles:
    - role: ssh_known_hosts
      tags: known_hosts

- name: Create certificates
  hosts: localhost
  roles:
    - role: ssl_certificates
      tags: ssl_certificates
