---
- name: Add SSH key to agent
  hosts: localhost
  tasks:
    - name: Add SSH key
      ansible.builtin.include_role:
        name: add_ssh_key

- name: Reboot machines
  hosts: private, haproxy
  tasks:
    - name: Reboot system
      become: true
      ansible.builtin.reboot:
