---
- name: Configure Loadbalancer
  hosts: loadbalancer
  remote_user: ubuntu
  roles:
    - role: loadbalancer

- name: Configure ChatOps
  hosts: chatops
  remote_user: ubuntu
  roles:
    - role: chatops
