---
- name: Create systemd-exporter group
  become: true
  ansible.builtin.group:
    name: systemd-exporter
    state: present

- name: Add ubuntu to systemd-exporter group
  become: true
  ansible.builtin.user:
    name: ubuntu
    groups: systemd-exporter
    append: true

- name: Reset connection for group changes
  ansible.builtin.meta: reset_connection

- name: Create a systemd-exporter user
  become: true
  ansible.builtin.user:
    name: systemd-exporter
    create_home: false
    group: systemd-exporter
    system: true

- name: Create systemd-exporter directory
  become: true
  ansible.builtin.file:
    path: /opt/filebeat
    state: directory
    mode: "0774"
    owner: systemd-exporter
    group: systemd-exporter

- name: Download and extract systemd-exporter
  become: true
  ansible.builtin.unarchive:
    src: "
      https://github.com/prometheus-community/systemd_exporter/releases/download/\
      v{{ systemd_exporter_version }}/systemd_exporter-{{ systemd_exporter_version }}.linux-amd64.tar.gz
    "
    dest: /tmp
    remote_src: true
    creates: "/opt/systemd-exporter/systemd-exporter"
    mode: "0774"
  notify:
    - Move Move systemd-exporter binaries

- name: Copy systemd-exporter service file
  become: true
  ansible.builtin.copy:
    src: systemd-exporter.service
    dest: /etc/systemd/system/systemd-exporter.service
    owner: systemd-exporter
    group: systemd-exporter
    mode: "0774"
  notify:
    - Start systemd-exporter

- name: Create systemd-exporter logging directory
  become: true
  ansible.builtin.file:
    path: /var/log/systemd-exporter
    state: directory
    mode: "0774"
    owner: systemd-exporter
    group: systemd-exporter

- name: Copy filebeat external config
  become: true
  ansible.builtin.copy:
    src: systemd-exporter.filebeat.yml
    dest: /var/filebeat/systemd-exporter.filebeat.yml
    owner: root
    group: root
    mode: "0640"
