---
- name: Move Prometheus binaries
  become: true
  ansible.builtin.copy:
    src: "/tmp/prometheus-{{ prometheus_version }}.linux-amd64/"
    dest: "/opt/prometheus"
    mode: preserve
    owner: prometheus
    group: prometheus
    remote_src: true

- name: Start Prometheus
  become: true
  ansible.builtin.systemd_service:
    name: prometheus.service
    state: started
    daemon_reload: true
    enabled: true

- name: Restart Prometheus
  become: true
  ansible.builtin.systemd_service:
    name: prometheus.service
    state: restarted
