variable "deployment" {}
variable "grafana_secgroup" {}
variable "chatops_secgroup" {}
variable "prometheus_secgroup" {}
variable "elasticsearch_secgroup" {}
variable "loadbalancer_secgroup" {}
variable "private_network" {}
variable "floating_ip" {}
variable "private_subnet" {}
variable "elasticsearch_volume_id" {}