plugin: openstack.cloud.openstack

all_projects: false
expand_hostvars: true
fail_on_errors: true
only_clouds:
  - "openstack"
strict: true
clouds_yaml_path: "~/.config/openstack/clouds.yaml"
replace_invalid_groups: true
only_ipv4: true
legacy_groups: false
inventory_hostname: "name"
groups:
  chatops: "(openstack.metadata.service | default('') == 'chatops') and (openstack.metadata.env | default('') == 'prod')"
  grafana: "(openstack.metadata.service | default('') == 'grafana') and (openstack.metadata.env | default('') == 'prod')"
  prometheus: "(openstack.metadata.service | default('') == 'prometheus') and (openstack.metadata.env | default('') == 'prod')"
  elastic: "(openstack.metadata.service | default('') == 'elastic') and (openstack.metadata.env | default('') == 'prod')"
  haproxy: "(openstack.metadata.service | default('') == 'haproxy') and (openstack.metadata.env | default('') == 'prod')"
