---
groups:
  - name: ChatOps rules
    rules:
      - alert: ChatOpsInstanceDown
        expr: time() - container_last_seen{name="chatops"} > 30
        for: 30s
        labels:
          severity: critical
        annotations:
          summary: "ChatOps container is detected down on {{ $labels.instance }}"
          description: "Container has been not running for more than 30 seconds."

      - alert: SystemdServiceDown
        expr: |
          systemd_unit_state{
            name=~"grafana-server.service|haproxy.service|kibana.service|elasticsearch.service|logstash.service|filebeat.service",state=~"failed|inactive"
          } == 1
        for: 30s
        labels:
          severity: critical
        annotations:
          summary: "Systemd service {{ $labels.name }} on host {{ $labels.instance }} is in state {{ $labels.state }}."
          description: "Systemd service has been in failed {{ $labels.state }} for 30s."
