---
- name: Move Alertmanager binaries
  become: true
  ansible.builtin.copy:
    src: "/tmp/alertmanager-{{ alertmanager_version }}.linux-amd64/"
    dest: "/opt/alertmanager"
    mode: preserve
    owner: alertmanager
    group: alertmanager
    remote_src: true

- name: Start Alertmanager
  become: true
  ansible.builtin.systemd_service:
    name: alertmanager.service
    state: started
    daemon_reload: true
    enabled: true

- name: Restart Alertmanager
  become: true
  ansible.builtin.systemd_service:
    name: alertmanager.service
    state: restarted
