---
- name: Move Elasticsearch binaries
  become: true
  ansible.builtin.copy:
    src: "/tmp/elasticsearch-{{ elasticsearch_version }}/"
    dest: "/opt/elasticsearch"
    mode: preserve
    owner: elastic
    group: elastic
    remote_src: true

- name: Start Elasticsearch
  become: true
  ansible.builtin.systemd_service:
    name: elasticsearch.service
    state: restarted
    daemon_reload: true
    enabled: true

- name: Restart Elasticsearch
  become: true
  ansible.builtin.systemd_service:
    name: elasticsearch.service
    state: restarted
