---
- name: Move Elasticsearch binaries
  become: true
  ansible.builtin.copy:
    src: "/tmp/elasticsearch-{{ elasticsearch_version }}/"
    dest: "/opt/elasticsearch"
    mode: preserve
    owner: elastic
    group: elastic
    remote_src: true

- name: Start Elasticsearch
  become: true
  ansible.builtin.systemd_service:
    name: elasticsearch.service
    state: restarted
    daemon_reload: true
    enabled: true

- name: Restart Elasticsearch
  become: true
  ansible.builtin.systemd_service:
    name: elasticsearch.service
    state: restarted

- name: Move Kibana binaries
  become: true
  ansible.builtin.copy:
    src: "/tmp/kibana-{{ kibana_version }}/"
    dest: "/opt/kibana"
    mode: preserve
    owner: elastic
    group: elastic
    remote_src: true

- name: Start Kibana
  become: true
  ansible.builtin.systemd_service:
    name: kibana.service
    state: restarted
    daemon_reload: true
    enabled: true

- name: Restart Kibana
  become: true
  ansible.builtin.systemd_service:
    name: kibana.service
    state: restarted

- name: Move Logstash binaries
  become: true
  ansible.builtin.copy:
    src: "/tmp/logstash-{{ logstash_version }}/"
    dest: "/opt/logstash"
    mode: preserve
    owner: elastic
    group: elastic
    remote_src: true

- name: Start Logstash
  become: true
  ansible.builtin.systemd_service:
    name: logstash.service
    state: started
    daemon_reload: true
    enabled: true

- name: Restart Logstash
  become: true
  ansible.builtin.systemd_service:
    name: logstash.service
    state: restarted
