---
- name: Restart Elasticsearch
  become: true
  ansible.builtin.systemd_service:
    name: elasticsearch.service
    state: restarted

- name: Restart Kibana
  become: true
  ansible.builtin.systemd_service:
    name: kibana.service
    state: restarted

- name: Restart Logstash
  become: true
  ansible.builtin.systemd_service:
    name: logstash.service
    state: restarted
