---
- name: Attach volume to stack host
  block:
    - name: Try sdb
      become: true
      ansible.posix.mount:
        boot: true
        path: /var/stack
        src: /dev/sdb
        state: mounted
        fstype: ext4
  rescue:
    - name: Try vdb
      become: true
      ansible.posix.mount:
        boot: true
        path: /var/stack
        src: /dev/vdb
        state: mounted
        fstype: ext4

- name: Set permissions
  become: true
  ansible.builtin.file:
    state: directory
    path: /var/stack
    owner: ubuntu
    group: ubuntu
    mode: "0775"
