#!/bin/bash
export IRIS_CLIENT_ID=
export IRIS_CLIENT_SECRET=
export PROD_INFLUX_USERNAME=
export PROD_INFLUX_PASSWORD=
export PROD_OPENSEARCH_PASSWORD=
export PROD_INFLUX_DB_URL=
export PROD_OPENSEARCH_URL=
export GRAFANA_DOMAIN_NAME=
export GRAFANA_ROOT_URL=

