---
- name: Refresh inventory to grab latest changes
  ansible.builtin.meta: refresh_inventory

- name: Remove FIP from known hosts
  ansible.builtin.known_hosts:
    name: "{{ item }}"
    state: absent
  loop:
    - "{{ terraform_floating_ip }}"
    - "{{ domain }}"

- name: Wait for VMs to be ready
  ansible.builtin.wait_for:
    timeout: 10

- name: Add FIP fingerprint to known hosts
  ansible.builtin.known_hosts:
    name: "{{ item }}"
    state: present
    key: "{{ lookup('ansible.builtin.pipe', 'ssh-keyscan {{ item }}') }}"
  loop:
    - "{{ terraform_floating_ip }}"
    - "{{ domain }}"
