---
- name: Install Prometheus
  become: true
  ansible.builtin.apt:
    name: prometheus
    state: latest # noqa: package-latest

- name: Set permissions on volume
  become: true
  ansible.builtin.file:
    path: /var/stack/prometheus/data
    state: directory
    owner: prometheus
    group: prometheus
    mode: "0774"
    recurse: true

- name: Copy prometheus rules file
  become: true
  ansible.builtin.copy:
    src: rules.yml
    dest: /etc/prometheus/rules.yml
    owner: prometheus
    group: prometheus
    mode: "0774"

- name: Copy systemd arguments
  become: true
  ansible.builtin.copy:
    src: prometheus
    dest: "/etc/default/prometheus"
    owner: prometheus
    group: prometheus
    mode: "0644"

- name: Template prometheus config
  become: true
  ansible.builtin.template:
    src: "{{ item }}"
    dest: "/etc/prometheus/{{ item[:-3] }}"
    owner: prometheus
    group: prometheus
    mode: "0774"
  loop:
    - prometheus.yml.j2
    - prometheus-web.yml.j2

- name: Copy certificate and key
  become: true
  ansible.builtin.copy:
    src: "./{{ env }}_ssl/{{ item }}"
    dest: "/etc/prometheus/{{ item }}"
    owner: prometheus
    group: prometheus
    mode: "0440"
  loop:
    - prometheus.key
    - prometheus.crt
    - alertmanager.crt

- name: Restart Prometheus
  become: true
  ansible.builtin.systemd_service:
    name: prometheus.service
    state: restarted
    daemon_reload: true

- name: Copy filebeat external config
  become: true
  ansible.builtin.copy:
    src: prometheus.filebeat.yml
    dest: /var/filebeat/prometheus.filebeat.yml
    owner: prometheus
    group: prometheus
    mode: "0640"
