---
- name: Create prometheus group
  become: true
  ansible.builtin.group:
    name: prometheus
    state: present

- name: Add ubuntu to prometheus group
  become: true
  ansible.builtin.user:
    name: ubuntu
    group: prometheus

- name: Reset connection for group changes
  ansible.builtin.meta: reset_connection

- name: Create a prometheus user
  become: true
  ansible.builtin.user:
    name: prometheus
    create_home: false
    group: prometheus
    system: true

- name: Download and extract Prometheus
  become: true
  ansible.builtin.unarchive:
    src: "
      https://github.com/prometheus/prometheus/releases/download/v{{ prometheus_version }}/\
      prometheus-{{ prometheus_version }}.linux-amd64.tar.gz
    "
    dest: /tmp
    remote_src: true
    creates: "/opt/prometheus"
    mode: "0774"
    notify:
      - Move Prometheus binaries
      - Start Prometheus

- name: Attach volume to Prometheus data directory
  become: true
  ansible.posix.mount:
    boot: true
    path: /var/prometheus/data
    src: "{{ prometheus_device }}"
    state: mounted
    fstype: ext4

- name: Set permissions on volume
  become: true
  ansible.builtin.file:
    path: /var/prometheus/data
    state: directory
    owner: prometheus
    group: prometheus
    mode: "0774"

- name: Copy prometheus service file
  become: true
  ansible.builtin.copy:
    src: prometheus.service
    dest: /etc/systemd/system/prometheus.service
    owner: prometheus
    group: prometheus
    mode: "0774"
    notify:
      - Start Prometheus

- name: Copy prometheus rules file
  become: true
  ansible.builtin.copy:
    src: rules.yml
    dest: /opt/prometheus/rules.yml
    owner: prometheus
    group: prometheus
    mode: "0774"
    notify:
      - Restart Prometheus

- name: Template prometheus config
  become: true
  ansible.builtin.template:
    src: "{{ item }}"
    dest: "/opt/prometheus/{{ item[:-3] }}"
    owner: prometheus
    group: prometheus
    mode: "0774"
    notify:
      - Restart Prometheus
  loop:
    - prometheus.yml.j2
    - web.yml.j2

- name: Create Prometheus log directory
  ansible.builtin.file:
    path: /var/log/prometheus
    state: directory
    owner: prometheus
    group: prometheus
    mode: "0770"
