---
- name: Move node-exporter binaries
  become: true
  ansible.builtin.copy:
    src: "/tmp/node_exporter-{{ node_exporter_version }}.linux-amd64/"
    dest: "/opt/node-exporter"
    mode: preserve
    owner: node-exporter
    group: node-exporter
    remote_src: true

- name: Start node-exporter
  become: true
  ansible.builtin.systemd_service:
    name: node-exporter.service
    state: restarted
    daemon_reload: true
    enabled: true
