---
- name: Install Alertmanager
  become: true
  ansible.builtin.apt:
    name: prometheus-alertmanager
    state: latest # noqa: package-latest

- name: Template alertmanager config
  become: true
  ansible.builtin.template:
    src: "{{ item }}"
    dest: "/etc/prometheus/{{ item[:-3] }}"
    owner: prometheus
    group: prometheus
    mode: "0770"
  loop:
    - alertmanager.yml.j2
    - alertmanager-web.yml.j2

- name: Copy systemd arguments
  become: true
  ansible.builtin.copy:
    src: prometheus-alertmanager
    dest: "/etc/default/prometheus-alertmanager"
    owner: prometheus
    group: prometheus
    mode: "0644"

- name: Copy certificate and key
  become: true
  ansible.builtin.copy:
    src: "./{{ env }}_ssl/alertmanager.{{ item }}"
    dest: "/etc/prometheus/alertmanager.{{ item }}"
    owner: prometheus
    group: prometheus
    mode: "0440"
  loop:
    - crt
    - key

- name: Restart Alertmanager
  become: true
  ansible.builtin.systemd_service:
    name: prometheus-alertmanager.service
    state: restarted
    daemon_reload: true

- name: Copy filebeat external config
  become: true
  ansible.builtin.copy:
    src: alertmanager.filebeat.yml
    dest: /var/filebeat/alertmanager.filebeat.yml
    owner: prometheus
    group: prometheus
    mode: "0640"
