---
- name: Install prerequisite packages
  become: true
  ansible.builtin.apt:
    pkg:
      - apt-transport-https
      - software-properties-common
      - wget
    update_cache: true

- name: Create key directory
  become: true
  ansible.builtin.file:
    path: /etc/apt/keyrings
    state: directory
    mode: "0755"

- name: Add Grafana key and repository to apt
  become: true
  block:
    - name: Add key
      ansible.builtin.get_url:
        url: https://apt.grafana.com/gpg.key
        dest: /etc/apt/keyrings/grafana.asc
        mode: "0755"

    - name: Add repository
      ansible.builtin.apt_repository:
        repo: "deb [signed-by=/etc/apt/keyrings/grafana.asc] https://apt.grafana.com stable main"
        state: present

- name: Install Grafana OSS
  become: true
  ansible.builtin.apt:
    name: grafana
    update_cache: true

- name: Copy datasource file template
  become: true
  ansible.builtin.template:
    src: datasource.yml.j2
    dest: /etc/grafana/provisioning/datasources/datasource.yml
    owner: root
    group: grafana
    mode: "0644"

- name: Copy config file template
  become: true
  ansible.builtin.template:
    src: grafana.ini.j2
    dest: /etc/grafana/grafana.ini
    owner: root
    group: grafana
    mode: "0644"

- name: Copy dashboard file
  become: true
  ansible.builtin.copy:
    src: dashboard.yml
    dest: /etc/grafana/provisioning/dashboards/dashboard.yml
    owner: root
    group: grafana
    mode: "0644"

- name: Copy dashboards
  become: true
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "/etc/grafana/provisioning/dashboards/{{ item }}"
    owner: root
    group: grafana
    mode: "0777"
  loop:
    - chatops.json
    - haproxy.json
    - alerts.json
    - status.json

- name: Make sure grafana-server.service is running
  become: true
  ansible.builtin.systemd_service:
    state: restarted
    name: grafana-server.service

- name: Copy filebeat external config
  become: true
  ansible.builtin.copy:
    src: grafana.filebeat.yml
    dest: /var/filebeat/grafana.filebeat.yml
    owner: root
    group: root
    mode: "0640"
