---
- name: Extract Logstash
  ansible.builtin.unarchive:
    src: "
      https://artifacts.elastic.co/downloads/logstash/logstash-{{ logstash_version }}-linux-x86_64.tar.gz
      "
    dest: /tmp
    remote_src: true
    creates: /opt/logstash
    mode: "0774"
    notify:
      - Move Logstash binaries

- name: Copy logstash service file
  become: true
  ansible.builtin.copy:
    src: logstash.service
    dest: /etc/systemd/system/logstash.service
    owner: elastic
    group: elastic
    mode: '0774'
    notify:
      - Start Logstash

- name: Template logstash config
  become: true
  ansible.builtin.template:
    src: logstash.conf.j2
    dest: "/opt/logstash/config/logstash.conf"
    owner: elastic
    group: elastic
    mode: "0770"
    notify:
      - Restart Logstash

- name: Copy certificate and key
  become: true
  ansible.builtin.copy:
    src: "./SSL/{{ item }}"
    dest: "/opt/logstash/{{ item }}"
    owner: elastic
    group: elastic
    mode: "0440"
    notify:
      - Restart Logstash
  loop:
    - logstash.key
    - logstash.crt
    - elasticsearch.crt
