---
- name: Create / check the bastion public key file exists
  ansible.builtin.file:
    path: "../terraform/{{ env }}-bastion-key.pub"
    state: touch
    owner: "{{ ansible_env.USER }}"
    group: "{{ ansible_env.USER }}"
    mode: "0774"

- name: Create Terraform variables file
  ansible.builtin.template:
    src: terraform.tfvars.j2
    dest: "{{ playbook_dir }}/../terraform/terraform.tfvars"
    owner: "{{ ansible_env.USER }}"
    group: "{{ ansible_env.USER }}"
    mode: "0774"

- name: Destroy infrastructure
  community.general.terraform:
    project_path: "../terraform"
    state: absent
    complex_vars: true
    workspace: "{{ env }}"

- name: Remove generated files
  block:
    - name: Delete terraform.tfvars file
      ansible.builtin.file:
        path: "../terraform/terraform.tfvars"
        state: absent

    - name: Remove private key file
      ansible.builtin.file:
        path: "{{ env }}-bastion-key"
        state: absent

    - name: Remove public key file
      ansible.builtin.file:
        path: "../terraform/{{ env }}-bastion-key.pub"
        state: absent

    - name: Remove ssl directory
      ansible.builtin.file:
        path: "./{{ env }}_ssl"
        state: absent
