---
- name: Move systemd-exporter binaries
  become: true
  ansible.builtin.copy:
    src: "/tmp/systemd_exporter-{{ systemd_exporter_version }}.linux-amd64/"
    dest: "/opt/systemd-exporter"
    mode: preserve
    owner: systemd-exporter
    group: systemd-exporter
    remote_src: true

- name: Start systemd-exporter
  become: true
  ansible.builtin.systemd_service:
    name: systemd-exporter.service
    state: restarted
    daemon_reload: true
    enabled: true
