name: Black formatter

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        
      - name: Prometheus IP Script
        uses: psf/black@stable
        with:
          src: "prometheus_ip_script"

      - name: IRISCAST Energy Monitoring
        uses: psf/black@stable
        with:
          src: "iriscasttools/iriscasttools"

      - name: Aquilon Zombie Finder 
        uses: psf/black@stable
        with:
            src: "aq_zombie_finder"
          
      - name: DNS Entry Checker 
        uses: psf/black@stable
        with:
            src: "dns_entry_checker"

      - name: Word Cloud Generator 
        uses: psf/black@stable
        with:
            src: "word_cloud_generator"
         
      - name: JSM Metric Collection
        uses: psf/black@stable
        with:
            src: "jsm_metric_collection"

      - name: Openstack-Rally-Tester
        uses: psf/black@stable
        with:
            src: "OpenStack-Rally-Tester"
