name: Black formatter

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Rabbit Consumer
        uses: psf/black@stable
        with:
          src: "OpenStack-Rabbit-Consumer"

      - name: CAPI Image Builder
        uses: psf/black@stable
        with:
          src: "capi_image_builder"

      - name: Prometheus IP Script
        uses: psf/black@stable
        with:
          src: "prometheus_ip_script"

      - name: IRISCAST Energy Monitoring
        uses: psf/black@stable
        with:
          src: "iriscasttools/iriscasttools"
