name: DNS Entry Checker Unittest

on: 
  push:
    branches:
      - master
    paths:
      - "dns_entry_checker/**"
      - ".github/workflows/dns_entry_checker.yaml"
  pull_request:
    paths:
      - "dns_entry_checker/**"
      - ".github/workflows/dns_entry_checker.yaml"

jobs:
  test_with_unit_test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9"]
    steps:
      - uses: actions/checkout@v5
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: "pip"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r dns_entry_checker/requirements.txt
      - name: Test with unittest
        run: |
            cd dns_entry_checker
            python3 -m unittest discover -s ./test -p "test_*.py"