name: GPU Benchmark PR
on:
  push:
    branches:
      - master
    paths:
      - ".github/workflows/gpu_benchmark.yml"
      - "gpu_benchmark/**"
  pull_request:
    paths:
      - ".github/workflows/gpu_benchmark.yml"
      - "gpu_benchmark/**"

jobs:
  shellcheck:
    name: Shellcheck
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
      - name: Run ShellCheck
        uses: ludeeus/action-shellcheck@00cae500b08a931fb5698e11e79bfbd38e612a38
        with:
          scandir: "./gpu_benchmark"
