name: GPU Benchmark PR
on:
  push:
    branches:
      - master
    paths:
      - ".github/workflows/gpu_benchmark.yml"
      - "gpu_benchmark/**"
  pull_request:
    paths:
      - ".github/workflows/gpu_benchmark.yml"
      - "gpu_benchmark/**"

jobs:
  shellcheck:
    name: Shellcheck
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run ShellCheck
        uses: ludeeus/action-shellcheck@master
        with:
          scandir: "./gpu_benchmark"
