name: Openstack-Rally-Tester

on:
  push:
    branches:
      - master
    paths:
      - ".github/workflows/Openstack-Rally-Tester.yaml"
      - "OpenStack-Rally-Tester/**"
  pull_request:
    paths:
      - ".github/workflows/Openstack-Rally-Tester.yaml"
      - "OpenStack-Rally-Tester/**"

jobs:
  pylint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]
    steps:
      - uses: actions/checkout@v5
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: "pip"
      - name: Install dependencies
        run: |
          cd OpenStack-Rally-Tester && python -m pip install -r requirements.txt
          python -m pip install pylint
      
      - name: Analyse with pylint
        run: |
          cd OpenStack-Rally-Tester/usr/local/bin && pylint rally_extract_results.py

  shellcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Run ShellCheck
        uses: ludeeus/action-shellcheck@master
        with:
          scandir: "./OpenStack-Rally-Tester"
